### PR TITLE
Tests for feature labels and related warnings/messages

### PR DESCRIPTION
**Pull request by martinju**
Test for explanation and shapr

### CODE REVIEW

**Comment by martinju** [comment]
@nikolase90 I don't understand why the three test that fails does so. I thought silent meant no messages, warnings or errors? When I run the functions manually there is no output to the console. Any idea?

**Comment by martinju** [comment]
Hmm. devtools::test() does not fail locally with a clean environment. Don't know what the problem is now...

**Comment by nikolase90** [comment]
Fails when running `devtools::check()` locally. Will see if I can figure it out.

**Comment by nikolase90** [comment]
Let's just merge this one, and remove the failing things in `nikolai/feature_labels`.

**Pull request merged**
