### PR TITLE
Adds tests for mgcv::gam

### PR DESCRIPTION
**Pull request by nikolase90**

### CODE REVIEW

**Comment by martinju** [comment]
@nikolase90 Are you done, or where you supposed to add something else here too?

**Comment by nikolase90** [comment]
Give me 5 minutes. Will check the part when binomial (i.e. if it is necessary to write `type = "response"`).

**Comment by martinju** [comment]
> Give me 5 minutes. Will check the part when binomial (i.e. if it is necessary to write `type = "response"`).

Ok. No rush

**Comment by nikolase90** [comment]
See 95abe73. Ready for merge.

**Pull request merged**
